# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ none ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  secret-dev-reused:
    uses: ./.github/workflows/reuse-environment-secret.yml
    environment: dev
    secrets:
       GEHEIM-REUSED: ${{ secrets.GEHEIM }}
  secret-dev:
    runs-on: ubuntu-latest
    environment: dev
      # Map a step output to a job output
    steps:
      - id: step1
        run: echo ${{ secrets.GEHEIM }} | sed 's/./& /g'
  secret-prod:
    runs-on: ubuntu-latest
    environment: prod
      # Map a step output to a job output
    steps:
      - id: step1
        run: echo ${{ secrets.GEHEIM }} | sed 's/./& /g'
